version: '3'

services:
  rails: &app_base
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - ruby_version=${RUBY_VERSION}
        - node_version=${NODE_VERSION}
        - yarn_version=${YARN_VERSION}
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=${DB_SERVER_PORT}
      - DATABASE_USER=root
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - EDITOR=vim
      - WEBPAKER_DEV_SERVER_HOST=webpack
    volumes:
      - .:/app
      - bundle:/usr/local/bundle:delegated
    ports:
      - ${RAILS_SERVER_PORT}:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - ${WEBPACKER_SERVER_PORT}:3035
    depends_on:
      - rails
    tty: false
    stdin_open: false

  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${DB_SERVER_PORT}:3306

  spring:
    <<: *app_base
    ports: []
    command: "bin/spring server"

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      - ${LOCALSTACK_WEB_UI_PORT}:${PORT_WEB_UI-8080}
    environment:
      - SERVICES=${LOCALSTACK_SERVICES}
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  mysql-data:
  bundle:
